# ==============================================================================
# MAIN TMUX CONFIGURATION (~/.tmux.conf)
# ==============================================================================

# Core Settings for Terminal Compatibility
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start window/pane indexing at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# ==============================================================================
# VISUAL THEME HOOK (Sourced Dynamically from global theme engine)
# ==============================================================================
if-shell '[ -f ~/.config/tmux/colors.tmux ]' 'source-file ~/.config/tmux/colors.tmux'

# ==============================================================================
# PLUGINS (Managed via TPM)
# ==============================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Vim-Tmux-Navigator Plugin
set -g @plugin 'christoomey/vim-tmux-navigator'

# yank integration
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'laktak/extrakto' # fzf search and yank from buffer

# session managing
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# configure plugins
# Keep Neovim sessions alive inside tmux splits
set -g @resurrect-strategy-nvim 'session'
# Enable automatic restoration on boot
set -g @continuum-restore 'on'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @extrakto_key "f"
TMUX_FZF_LAUNCH_KEY="tab"

# Initialize TMUX plugin manager (Keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'

# ==============================================================================
# BINDINGS
# ==============================================================================

# vertical and horizontal spliting
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# yanking
unbind [
bind v copy-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-key -X begin-selection
bind-key -T copy-mode-vi C-v send-key -X rectangle-toggle
bind-key -T copy-mode-vi y send-key -X copy-selection-and-cancel
